### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by sentientcucumber** [jeff-flower/Majrix#10]
As a developer, I need a Leiningen project, so I can contribute to this amazing application.

**Comment by sentientcucumber** [comment]
This work entails
- Using Leiningen, create a new project.
- Add dependencies
  - midje
  - database library
  - compojure
  - marginalia
- ~~Set up database~~
- Document process to setup development environment

**Comment by jeff-flower** [comment]
It's safe to say this is done for now. Setup is documented, although it will always be an evolving process.
