### ISSUE TITLE
Document IDE Setup

### ISSUE THREAD

**Issue by sentientcucumber** [jeff-flower/Majrix#14]
Document IDE setup.
#### References
- [Clojure for the Brave and True](http://www.braveclojure.com/clojure-for-the-brave-and-true/)

**Comment by jeff-flower** [comment]
- Cursive IntelliJ plugin
  - https://cursive-ide.com/userguide/index.html
- Emacs setup
  - general system setup: http://www.braveclojure.com/getting-started/
  - emacs setup: www.braveclojure.com/basic-emacs/
- Counterclockwise Eclipse plugin
  - http://doc.ccw-ide.org/documentation.html
- Sublime Text
  - Note: you'll probably need to set up some things on your own such as Leiningen
  - https://spin.atomicobject.com/2016/04/08/sublime-text-clojure/

**Comment by jeff-flower** [comment]
Added notes to the readme on the develop branch.  I'm most familiar with emacs, so i know those notes are solid.  The documentation for cursive and eclipse looked solid, but people should add their own notes as they see fit going forward.  Closing this issue for now.
