### ISSUE TITLE
Define error interface between API and Database

### ISSUE THREAD

**Issue by sentientcucumber** [jeff-flower/Majrix#15]
Define an interface between the database and API layers to convey when errors occur. The database side should use Matrix error codes as keys to send to the API layer. The API layer should be able to interpolate those keys into what is sent back to the client. This way, the database layer doesn't need to worry what the client will see and the API layer doesn't need to concern itself with errors from the database side.
### Useful Links

[Neo4j Error Codes](http://neo4j.com/docs/developer-manual/current/reference/#status-codes)
### Example

``` clojure
{
    :successful? false
    :error :M_INVALID_USERNAME
}
```

**Comment by shellhead** [comment]
Some issues to think about:

- Since the transaction API allows us to submit multiple CYPHER queries,
