### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by sentientcucumber** [jeff-flower/Majrix#2]
As a user, I need a way to register, so I can use the service.

**Comment by sentientcucumber** [comment]
A client will send an HTTP POST request to a given endpoint on the server. The request will need to contain a user's kind (as a query parameter, we'll only be supporting user value for v1), auth (we will be using `m.login.dummy`), email, and username. The server will register the user in the database, creating a user record. The database record for a user will contain the user name and email. A 200 response will be sent to the user containing user_id, access_token, home_server, and refresh_token. The user will get a 400 back if the username is already taken, with either `M_USER_IN_USE` or `M_INVALID_USERNAME`.

The same route should be able to handle an empty POST request and no authentication. It should return information about the flows and stages.

##### References

http://matrix.org/docs/spec/client_server/r0.2.0.html#user-interactive-authentication-api
http://matrix.org/docs/api/client-server/#!/User_data/post_matrix_client_r0_register

**Comment by jeff-flower** [comment]
## MVP:
- API accepts POST w/required fields (not enforced)
- add user to database
- gen access token

## Request

```
{
  "auth": {type: "m.login.dummy"},
  "bind_email": boolean,
  "password": string,
  "username": string
}
```

## Response

```
{
  "user_id": string,
  "access_token": string,
  "home_server": string,
  "refresh_token": string
}
```

## Type of accounts

According to spec user and guest are both valid account types.  The account type is passed in as a query parameter and should default to user.  We will not be supporting guest accounts at this time.

## Access Tokens

Should be generated by a separate function.  For now plan on doing something simple like encrypting their username.  Add a placeholder function for access token verification but don't have it do any actual verification at this time.

~~## Database Protocol
Define a clojure protocol that we should expect to be implemented when adding new features that interface with the database.  We won't worry so much about what it should look like up front, but will add to it as we go.  For now, the protocol should have a function for adding to the database.~~

**Comment by jeff-flower** [comment]
Clarification on the API-DB interaction for adding a user

## Database Layer

### Return a true false indicator

Return a map for now, in the future we can switch this out for a record as we build more routes/functionality

`
{ :successful? bool }
`

### Issues

Need to research what the response status code and body look like on an error

## API Layer
- Expects the map response from the database layer
- Returns a response

### Successful Response

See previous comment for successful format

### Error

For now not interested in providing in depth error knowledge, in the future we will enhance error messages.  For more information on matrix errors, see the [matrix client-server spec](http://matrix.org/docs/spec/client_server/r0.2.0.html#api-standards)

`
{
  "errcode": "M_GENERIC_ERROR",
  "error": "There was an error handling your request"
}
`

**Comment by jeff-flower** [comment]
## REST Errors in Cypher

Because a cypher request is a transaction, it will always return a 200 response.  If there are any errors, the errors key of the response will contain a non-empty array of error objects.  If there are no errors, the errors key of the response will contain an empty array.  For more details, see the [Neo4j Developers Manual](http://neo4j.com/docs/developer-manual/current/http-api/#rest-api-handling-errors)

**Comment by sentientcucumber** [comment]
Sample response object for the API.

``` json
{
  "user_id": "@cheeky_monkey:matrix.org",
  "access_token": "abc123",
  "home_server": "matrix.org",
  "refresh_token": "def456"
}
```

**Comment by jeff-flower** [comment]
Error Handling:
DB Side: create a map with keyword = neo4j error string and value = majrix error code
API Side: create a map with keyword = majrix error code and value = client error response

**Comment by sentientcucumber** [comment]
As mentioned in a side conversation, the above can be problematic as one database code may relate to several API error codes. As great as this would be to make generic, it may not make sense to do so right now, until we've worked with the problem more.

**Comment by jeff-flower** [comment]
## Constraints in neo4j

Constraints are added to labels (either nodes or relationships)
1) REST endpoint: 

```
POST http://<db-name>/db/data/schema/constraint/<label to constrain>/uniqueness

request body:

{
    "property_keys" : ["<property to constrain>"]
}
```

2) CYPHER query
`CREATE CONSTRAINT ON (n:<label>) ASSERT n.<your property here> IS UNIQUE`

**Comment by jeff-flower** [comment]
## Neo4j error handling and transformation

### Notes

The matrix error code will be used as an internal error code for mapping errors from the db side to response sent from the api side to the user.  This supports modularity since any change to the db should not affect error handling by the api side.

### db.clj

If an error is present in the neo4j response body, transform the neo4j error to a matrix error code (like M_USER_IN_USE), add the matrix error to the response sent to handler.clj `{:error <matrix-error-code>}`

### handler.clj

If response map from db.clj contains an error code, use the matrix error code to look up the response and status that should be sent back to the user and add these to the api response

**Comment by jeff-flower** [comment]
cURL request so I don't have to think about it every. damn. time.

```
curl -H "Content-Type: application/json"  --data '{"username": "myusername"}' http://localhost:3000/_matrix/client/r0/register

```
